trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout the GitHub repository
- checkout: none
- script: |
    git config --global user.name "Azure Pipelines"
    git config --global user.email "justpwnedggez@gmail.com"
    git clone https://github.com/justpwnedggez/loan-sys.git
    cd loan-sys
    git checkout main
  displayName: 'Checkout GitHub main branch'

# Step 2: Push the changes to Azure DevOps repository
- script: |
    git remote add azure https://dev.azure.com/Capstone/_git/Capstone
    git fetch azure
    git checkout develop
    git merge origin/develop
    git push azure develop
  displayName: 'Merge GitHub main into Azure develop'

# You can add other build, test, or deployment steps here
